version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  python-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=dev
